# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9166dd2c90d43f1bd2eb16fcde2ab803cc7ae2224f06bef5a2e692bc784846f0e26829028efb12c47220e7f7240741a63408b6f45ec9333f4f3e39af93b578ba

test:
  secret_key_base: cc362cf7b2ad2ea845a071e4da108742aefc1e49d0c34ac446f3542aedced5c2f00cd20fd5d0f5279e37cd70d3171c0a2302303de070991a2d2d7b4306581ef3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
